name: Test Training

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Start Container
      run: docker-compose up -d --build

    - name: Install dependencies
      run: docker-compose exec -T test-training composer install

    - name: Run PHPCS-Fixer
      run: docker-compose exec -T test-training composer php-cs-fixer

    - name: Run PHPStam
      run: docker-compose exec -T test-training composer phpstan

    - name: Run PHPUnit Tests
      run: docker-compose exec -T test-training composer test

    - name: Down Container
      run: docker-compose down
